ekf_local:
  ros__parameters:
    use_sim_time: true
    frequency: 30.0
    two_d_mode: true

    base_link_frame: base_footprint
    odom_frame: odom
    world_frame: odom        # ✅ 로컬 EKF는 반드시 odom

    # IMU
    imu0: /imu/with_cov
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  true,  true,  true,
                  false, false, false]
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true

    # Gazebo wheel odom
    odom0: /odom
    odom0_config: [true,  true,  false,
                   false, false, false,
                   true,  true,  false,
                   false, false, false,
                   false, false, false]
    odom0_differential: false

    process_noise_covariance_diagonal:
      [0.05, 0.05, 1.0,
       0.01, 0.01, 0.01,
       0.5,  0.5,  1.0,
       0.1,  0.1,  0.2,
       0.5,  0.5,  1.0]

    publish_tf: true          # ✅ odom→base_footprint
    publish_acceleration: false
