ekf_global:
  ros__parameters:
    use_sim_time: true
    frequency: 30.0
    two_d_mode: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: map

    # 로컬 EKF 출력(연속, 소규모 드리프트) → odometry/filtered
    odom0: /odometry/filtered_local
    odom0_config: [true, true, false,
                   false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom0_differential: false

    # navsat 변환 GPS(비연속, 절대 정합) → gps/odom (이제 frame_id=map)
    odom1: /gps/odom
    odom1_config: [true, true, false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom1_differential: false

    # 자세는 IMU로 보정
    imu0: /imu/with_cov
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    imu0_differential: false

    publish_tf: true
    publish_acceleration: false
