navsat_transform:
  ros__parameters:
    frequency: 30.0
    delay: 0.0

    # 프레임 지정
    base_link_frame: base_footprint
    odom_frame: odom
    world_frame: odom

    # 동작 옵션
    use_odometry_yaw: true
    two_d_mode: true
    zero_altitude: true

    publish_filtered_gps: true
    publish_heading: false
    wait_for_datum: false

    magnetic_declination_radians: 0.0
    yaw_offset: 0.0

    use_sim_time: true
