<?xml version="1.0"?>
<robot name="henes_t870" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ===== Geometry (Henes T870) ===== -->
  <xacro:property name="body_x" value="1.28"/>
  <xacro:property name="body_y" value="0.775"/>
  <xacro:property name="body_z" value="0.30"/>

  <xacro:property name="wheel_r"   value="0.135"/>
  <xacro:property name="wheel_len" value="0.11"/>

  <xacro:property name="front_axle_x" value="0.32"/>
  <xacro:property name="rear_axle_x"  value="-0.39"/>
  <xacro:property name="track_width"  value="0.70"/>
  <xacro:property name="wheel_y"      value="${track_width/2.0}"/>

  <!-- base_footprint(z=0) 기준 배치 -->
  <xacro:property name="body_center_z" value="${wheel_r + body_z/2.0}"/>
  <xacro:property name="wheel_z_offset" value="${wheel_r - body_center_z}"/>

  <!-- body collision 슬림 -->
  <xacro:property name="body_collision_y_margin" value="0.02"/>
  <xacro:property name="body_collision_y" value="${ 2*( wheel_y - wheel_len/2.0 - body_collision_y_margin ) }"/>

  <!-- ===== Materials ===== -->
  <material name="mat_red">    <color rgba="1 0 0 1"/></material>
  <material name="mat_yellow"> <color rgba="1 1 0 1"/></material>
  <material name="mat_black">  <color rgba="0.1 0.1 0.1 1"/></material>

  <!-- ===== Mass/Inertia ===== -->
  <xacro:property name="m_body"  value="12.0"/>
  <xacro:property name="m_wheel" value="0.8"/>

  <xacro:property name="Ixx_body" value="${(1.0/12.0)*m_body*(body_y*body_y + body_z*body_z)}"/>
  <xacro:property name="Iyy_body" value="${(1.0/12.0)*m_body*(body_x*body_x + body_z*body_z)}"/>
  <xacro:property name="Izz_body" value="${(1.0/12.0)*m_body*(body_x*body_x + body_y*body_y)}"/>

  <xacro:property name="I_long" value="${(1.0/12.0)*m_wheel*(3.0*wheel_r*wheel_r + wheel_len*wheel_len)}"/>
  <xacro:property name="I_spin" value="${0.5*m_wheel*wheel_r*wheel_r}"/>

  <xacro:macro name="inertia_wheel">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${m_wheel}"/>
      <inertia ixx="${I_long}" ixy="0" ixz="0" iyy="${I_spin}" iyz="0" izz="${I_long}"/>
    </inertial>
  </xacro:macro>

  <!-- Gazebo 추가설정 -->
  <xacro:include filename="$(find mobile_robot)/model/robot.gazebo"/>
  <xacro:add_gz/>

  <!-- ===== Frames ===== -->
  <link name="base_footprint"/>
  <joint name="body_fixed" type="fixed">
    <parent link="base_footprint"/>
    <child  link="body_link"/>
    <origin xyz="0 0 ${body_center_z}" rpy="0 0 0"/>
  </joint>

  <!-- ===== Body ===== -->
  <link name="body_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="${body_x} ${body_y} ${body_z}"/></geometry>
      <material name="mat_red"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="${body_x} ${body_collision_y} ${body_z}"/></geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${m_body}"/>
      <inertia ixx="${Ixx_body}" ixy="0" ixz="0" iyy="${Iyy_body}" iyz="0" izz="${Izz_body}"/>
    </inertial>
  </link>

  <!-- ===== Rear Wheels (as before) ===== -->
  <joint name="wheel1_joint" type="continuous">
    <parent link="body_link"/><child link="wheel1_link"/>
    <origin xyz="${rear_axle_x} -${wheel_y} ${wheel_z_offset}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/><limit effort="1000" velocity="1000"/><dynamics damping="2.0" friction="0.0"/>
  </joint>
  <link name="wheel1_link">
    <visual><origin xyz="0 0 0" rpy="1.570795 0 0"/><geometry><cylinder radius="${wheel_r}" length="${wheel_len}"/></geometry><material name="mat_yellow"/></visual>
    <collision><origin xyz="0 0 0" rpy="1.570795 0 0"/><geometry><cylinder radius="${wheel_r}" length="${wheel_len}"/></geometry></collision>
    <xacro:inertia_wheel/>
  </link>

  <joint name="wheel2_joint" type="continuous">
    <parent link="body_link"/><child link="wheel2_link"/>
    <origin xyz="${rear_axle_x} ${wheel_y} ${wheel_z_offset}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/><limit effort="1000" velocity="1000"/><dynamics damping="2.0" friction="0.0"/>
  </joint>
  <link name="wheel2_link">
    <visual><origin xyz="0 0 0" rpy="1.570795 0 0"/><geometry><cylinder radius="${wheel_r}" length="${wheel_len}"/></geometry><material name="mat_yellow"/></visual>
    <collision><origin xyz="0 0 0" rpy="1.570795 0 0"/><geometry><cylinder radius="${wheel_r}" length="${wheel_len}"/></geometry></collision>
    <xacro:inertia_wheel/>
  </link>

  <!-- ===== Front Wheels with Steering ===== -->
  <!-- FR knuckle (스티어링 허브) -->
  <link name="fr_knuckle_link">
    <!-- 작은 실린더(장식/충돌) -->
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><cylinder radius="0.03" length="0.06"/></geometry>
      <material name="mat_black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><cylinder radius="0.03" length="0.06"/></geometry>
    </collision>
    <!-- 가벼운 관성(실린더 근사) -->
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.2"/>
      <inertia ixx="1.05e-4" ixy="0" ixz="0" iyy="1.05e-4" iyz="0" izz="9.0e-5"/>
    </inertial>
  </link>

  <joint name="fr_steer_joint" type="revolute">
    <parent link="body_link"/>
    <child  link="fr_knuckle_link"/>
    <origin xyz="${front_axle_x} -${wheel_y} ${wheel_z_offset}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.628" upper="0.628" effort="120" velocity="2.0"/>
    <dynamics damping="0.4"/>
  </joint>

  <joint name="fr_wheel_joint" type="continuous">
    <parent link="fr_knuckle_link"/>
    <child  link="wheel3_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000"/><dynamics damping="2.0" friction="0.0"/>
  </joint>

  <link name="wheel3_link">
    <visual><origin xyz="0 0 0" rpy="1.570795 0 0"/><geometry><cylinder radius="${wheel_r}" length="${wheel_len}"/></geometry><material name="mat_yellow"/></visual>
    <collision><origin xyz="0 0 0" rpy="1.570795 0 0"/><geometry><cylinder radius="${wheel_r}" length="${wheel_len}"/></geometry></collision>
    <xacro:inertia_wheel/>
  </link>

  <!-- FL knuckle -->
  <link name="fl_knuckle_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><cylinder radius="0.03" length="0.06"/></geometry>
      <material name="mat_black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><cylinder radius="0.03" length="0.06"/></geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.2"/>
      <inertia ixx="1.05e-4" ixy="0" ixz="0" iyy="1.05e-4" iyz="0" izz="9.0e-5"/>
    </inertial>
  </link>

  <joint name="fl_steer_joint" type="revolute">
    <parent link="body_link"/>
    <child  link="fl_knuckle_link"/>
    <origin xyz="${front_axle_x} ${wheel_y} ${wheel_z_offset}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.628" upper="0.628" effort="120" velocity="2.0"/>
    <dynamics damping="0.4"/>
  </joint>

  <joint name="fl_wheel_joint" type="continuous">
    <parent link="fl_knuckle_link"/>
    <child  link="wheel4_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000"/><dynamics damping="2.0" friction="0.0"/>
  </joint>

  <link name="wheel4_link">
    <visual><origin xyz="0 0 0" rpy="1.570795 0 0"/><geometry><cylinder radius="${wheel_r}" length="${wheel_len}"/></geometry><material name="mat_yellow"/></visual>
    <collision><origin xyz="0 0 0" rpy="1.570795 0 0"/><geometry><cylinder radius="${wheel_r}" length="${wheel_len}"/></geometry></collision>
    <xacro:inertia_wheel/>
  </link>

  <!-- LiDAR -->
  <link name="lidar_link">
    <visual><geometry><cylinder radius="0.05" length="0.04"/></geometry><material name="mat_black"/></visual>
    <collision><geometry><cylinder radius="0.05" length="0.04"/></geometry></collision>
    <inertial><mass value="0.1"/><inertia ixx="1e-4" ixy="0" ixz="0" iyy="1e-4" iyz="0" izz="1e-4"/></inertial>
  </link>
  <joint name="lidar_joint" type="fixed">
    <parent link="body_link"/><child link="lidar_link"/>
    <origin xyz="0.25 0 0.30" rpy="0 0 0"/>
  </joint>


    <!-- ===== IMU (link + fixed joint) ===== -->
  <link name="imu_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="0.05 0.05 0.02"/></geometry>
      <material name="mat_black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="0.05 0.05 0.02"/></geometry>
    </collision>
    <!-- 작은 질량/관성: URDF->SDF 변환 시 링크/조인트 드랍 방지 -->
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.05"/>
      <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
    </inertial>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="body_link"/>
    <child  link="imu_link"/>
    <!-- 바디 중앙 근처에 부착 -->
    <origin xyz="0 0 0.10" rpy="0 0 0"/>
  </joint>

    <!-- ===== Camera (front RGB) ===== -->
  <link name="camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="0.06 0.06 0.04"/></geometry>
      <material name="mat_black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="0.06 0.06 0.04"/></geometry>
    </collision>
    <!-- URDF->SDF 변환 시 드랍 방지용 관성 -->
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.08"/>
      <inertia ixx="1.5e-5" ixy="0" ixz="0" iyy="1.5e-5" iyz="0" izz="1.5e-5"/>
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="body_link"/>
    <child  link="camera_link"/>
    <!-- 차체 전면 상단 근처 -->
    <origin xyz="0.40 0.00 0.20" rpy="0 0 0"/>
  </joint>

    <!-- ===== GPS (NavSat) ===== -->
  <link name="gps_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="0.05 0.05 0.02"/></geometry>
      <material name="mat_black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="0.05 0.05 0.02"/></geometry>
    </collision>
    <!-- URDF->SDF 드랍 방지용 최소 관성 -->
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.05"/>
      <inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5"/>
    </inertial>
  </link>

  <joint name="gps_joint" type="fixed">
    <parent link="body_link"/>
    <child  link="gps_link"/>
    <!-- 지붕 근처(카메라와 간섭 없게 약간 뒤로) -->
    <origin xyz="0.20 0.10 0.30" rpy="0 0 0"/>
  </joint>




</robot>
